# Tên ứng dụng
spring.application.name=UniPath-api

# Cấu hình kết nối Database PostgreSQL (ĐÃ ĐỔI THÀNH postgres Ở CUỐI)
spring.datasource.url=jdbc:postgresql://localhost:5433/UniPath
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect